AddCSLuaFile()

ROUND_WAIT      = 1
ROUND_PREPARE   = 2
ROUND_ACTIVE    = 3
ROUND_OVER      = 4

NET_PLAYER_JOIN             = "PlayerJoin"
NET_ROUND_STATUS_ON_JOIN    = "RoundStatusOnJoin"
NET_ROUND_STATUS_UPDATE     = "UpdateRoundStatus"
NET_ROUND_WINNER            = "RoundWinner"
NET_ROUND_PLAYER_LOSE       = "PlayerLose"
NET_ROUND_SEND_END_TIME     = "RoundEndTime"

PREP_TIME = 5
END_TIME = 5
ROUND_TIME = 180

MIN_PCT_TILES_FOR_OWNERSHIP_VICTORY = 0.75
